# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ZJHNetwork' do

pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'

end

